type: hulu_med
# model_path: /local/scratch/clo37/models/Hulu-Med-32B
model_path: ZJU-AI4H/Hulu-Med-32B
adapter_path: null


# for hulu_med: 
# member_set = /local/scratch/clo37/datasets/PubMedVision
# nonmember_set = 